name: cd

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ORACLE_HOME: /opt/instantclient_21_12
      LD_LIBRARY_PATH: /opt/instantclient_21_12
      OCI_DIR: /opt/instantclient_21_12
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8

    steps:
    - name: Checkout current code
      uses: actions/checkout@v4

    - name: Install Oracle instant client
      run: |
        mkdir -p /opt && cd /opt
        curl https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-basiclite-linux.x64-23.7.0.25.01.zip --output instantclient.zip
        curl https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-sdk-linux.x64-23.7.0.25.01.zip --output instantclient_sdk.zip
        unzip -o instantclient.zip
        unzip -o instantclient_sdk.zip

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler: latest
        bundler-cache: true
        cache-version: 1

    - name: Push to Rubygems
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "thomas.steiner@ikey.ch"
        git config --global user.name "thomis"
        mkdir ~/.gem
        echo -e "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        bundle exec rake release
        rm ~/.gem/credentials
